export const sampleRecusalPacket = {
  generatedAt: "2026-05-22T03:00:00.000Z",
  project: {
    id: "proj-neuro-graph-biomarkers",
    title: "Neural graph biomarkers for early intervention response",
    domain: "neuroscience",
    anonymousReviewMode: "double_blind",
    highImpactReputationWeight: true,
    authorIds: ["user-ada", "user-ben", "user-cora"],
    institutionIds: ["inst-northlake", "inst-bay-med"],
    grantIds: ["grant-ninds-2214"],
    challengeIds: ["challenge-open-neuro-26"],
  },
  users: [
    {
      id: "user-ada",
      name: "Ada Nguyen",
      active: true,
      institutionId: "inst-northlake",
      labId: "lab-graph-neuro",
      roles: ["author"],
    },
    {
      id: "user-ben",
      name: "Ben Ortiz",
      active: true,
      institutionId: "inst-bay-med",
      labId: "lab-imaging",
      roles: ["author"],
    },
    {
      id: "user-cora",
      name: "Cora Stein",
      active: true,
      institutionId: "inst-northlake",
      labId: "lab-graph-neuro",
      roles: ["author"],
    },
    {
      id: "rev-lina",
      name: "Lina Park",
      active: true,
      institutionId: "inst-west",
      labId: "lab-open-methods",
      reviewerTier: "trusted_reviewer",
      completedReviews: 34,
      averageCalibrationScore: 0.91,
      disclosureUpdatedAt: "2026-05-01",
    },
    {
      id: "rev-mateo",
      name: "Mateo Silva",
      active: true,
      institutionId: "inst-northlake",
      labId: "lab-graph-neuro",
      reviewerTier: "trusted_reviewer",
      completedReviews: 41,
      averageCalibrationScore: 0.88,
      disclosureUpdatedAt: "2026-05-15",
    },
    {
      id: "rev-nadia",
      name: "Nadia Iqbal",
      active: true,
      institutionId: "inst-coastal",
      labId: "lab-repro",
      reviewerTier: "reviewer",
      completedReviews: 16,
      averageCalibrationScore: 0.79,
      disclosureUpdatedAt: "2025-09-01",
    },
    {
      id: "rev-oscar",
      name: "Oscar Moreno",
      active: true,
      institutionId: "inst-bay-med",
      labId: "lab-translational",
      reviewerTier: "trusted_reviewer",
      completedReviews: 22,
      averageCalibrationScore: 0.83,
      disclosureUpdatedAt: "2026-04-20",
    },
    {
      id: "rev-priya",
      name: "Priya Shah",
      active: false,
      institutionId: "inst-east",
      labId: "lab-clinical",
      reviewerTier: "reviewer",
      completedReviews: 9,
      averageCalibrationScore: 0.68,
      disclosureUpdatedAt: "2024-12-18",
    },
  ],
  relationships: [
    {
      reviewerId: "rev-mateo",
      authorId: "user-ada",
      type: "same_lab",
      startedAt: "2024-08-01",
      evidence: "Current lab roster places reviewer and author in lab-graph-neuro.",
    },
    {
      reviewerId: "rev-mateo",
      authorId: "user-cora",
      type: "mentor_student",
      startedAt: "2024-08-01",
      evidence: "Reviewer is listed as project methods mentor.",
    },
    {
      reviewerId: "rev-nadia",
      authorId: "user-ben",
      type: "coauthorship",
      startedAt: "2025-03-12",
      evidence: "Shared preprint DOI 10.5555/neuro.2025.14.",
    },
    {
      reviewerId: "rev-oscar",
      authorId: "user-ben",
      type: "shared_institution",
      startedAt: "2026-01-01",
      evidence: "Same institution for double-blind review.",
    },
    {
      reviewerId: "rev-oscar",
      authorId: "user-ben",
      type: "shared_grant",
      startedAt: "2026-02-10",
      evidence: "Both are named personnel on grant-ninds-2214.",
    },
    {
      reviewerId: "rev-lina",
      authorId: "user-cora",
      type: "prior_public_comment",
      startedAt: "2025-09-05",
      evidence: "Prior public methods question on an earlier project version.",
    },
  ],
  assignments: [
    {
      id: "assign-lina",
      reviewerId: "rev-lina",
      reviewType: "methods_reproducibility",
      mode: "double_blind",
      reputationWeight: 0.22,
      publicImpact: "profile_and_project",
      requestedAt: "2026-05-21",
    },
    {
      id: "assign-mateo",
      reviewerId: "rev-mateo",
      reviewType: "technical_rigor",
      mode: "double_blind",
      reputationWeight: 0.34,
      publicImpact: "profile_and_leaderboard",
      requestedAt: "2026-05-21",
    },
    {
      id: "assign-nadia",
      reviewerId: "rev-nadia",
      reviewType: "statistical_methods",
      mode: "public",
      reputationWeight: 0.18,
      publicImpact: "profile_only",
      requestedAt: "2026-05-21",
    },
    {
      id: "assign-oscar",
      reviewerId: "rev-oscar",
      reviewType: "clinical_translation",
      mode: "double_blind",
      reputationWeight: 0.28,
      publicImpact: "profile_and_project",
      requestedAt: "2026-05-21",
    },
    {
      id: "assign-priya",
      reviewerId: "rev-priya",
      reviewType: "domain_review",
      mode: "public",
      reputationWeight: 0.12,
      publicImpact: "profile_only",
      requestedAt: "2026-05-21",
    },
  ],
}
