export const sampleGovernancePacket = {
  generatedAt: "2026-05-22T02:45:00.000Z",
  project: {
    id: "proj-neuro-crispr-042",
    title: "Neuro CRISPR longitudinal atlas",
    visibility: "institutional-only",
    institutionDomains: ["neuro.example.edu", "lab.example.org"],
    restrictedArtifactIds: ["dataset-human-rnaseq", "notebook-review-blinded"],
    protectedActions: [
      "restricted-data:download",
      "dataset:delete",
      "manuscript:publish",
      "project:archive",
    ],
  },
  owners: [
    {
      id: "u-owner-alvarez",
      role: "Owner",
      active: true,
      mfaVerified: true,
      institutionDomain: "neuro.example.edu",
    },
    {
      id: "u-admin-patel",
      role: "Admin",
      active: true,
      mfaVerified: true,
      institutionDomain: "lab.example.org",
    },
  ],
  serviceAccounts: [
    {
      id: "svc-notebook-rerun",
      displayName: "Notebook rerun worker",
      kind: "service_account",
      ownerSponsorId: "u-owner-alvarez",
      requesterId: "u-admin-patel",
      requesterMfaVerified: true,
      integrationType: "internal_worker",
      integrationVerified: true,
      purpose: "Scheduled notebook reruns for reproducibility checks",
      requestedAt: "2026-05-20T14:00:00.000Z",
      expiresAt: "2026-07-19T00:00:00.000Z",
      lastRotatedAt: "2026-05-20T14:00:00.000Z",
      scopes: ["notebook:run", "dataset:read", "artifact:write", "audit:append"],
      objectGrants: [
        {
          artifactId: "notebook-qc-pipeline",
          permission: "execute",
          dataClass: "code",
          approvedUseCase: "reproduce-results",
        },
        {
          artifactId: "dataset-public-qc",
          permission: "read",
          dataClass: "public_dataset",
          approvedUseCase: "reproduce-results",
        },
      ],
      approvalEvents: ["requested", "owner_approved", "security_reviewed", "issued"],
    },
    {
      id: "tok-orcid-profile-sync",
      displayName: "ORCID profile sync token",
      kind: "api_token",
      ownerSponsorId: "u-owner-alvarez",
      requesterId: "u-owner-alvarez",
      requesterMfaVerified: true,
      integrationType: "external_oauth",
      integrationVerified: true,
      purpose: "Refresh publication and affiliation metadata for researcher profiles",
      requestedAt: "2026-04-01T11:00:00.000Z",
      expiresAt: "2026-08-01T00:00:00.000Z",
      lastRotatedAt: "2026-03-15T11:00:00.000Z",
      scopes: ["profile:read", "profile:write", "audit:append"],
      objectGrants: [
        {
          artifactId: "profile-u-owner-alvarez",
          permission: "write",
          dataClass: "profile_metadata",
          approvedUseCase: "orcid-sync",
        },
      ],
      approvalEvents: ["requested", "owner_approved", "issued"],
    },
    {
      id: "tok-vendor-export",
      displayName: "External vendor export bridge",
      kind: "api_token",
      ownerSponsorId: null,
      requesterId: "u-former-contractor",
      requesterMfaVerified: false,
      integrationType: "external_vendor",
      integrationVerified: false,
      purpose: "Bulk export data to a visualization vendor",
      requestedAt: "2026-02-01T09:00:00.000Z",
      expiresAt: null,
      lastRotatedAt: "2025-11-01T09:00:00.000Z",
      scopes: ["*", "restricted-data:download", "dataset:delete", "project:admin"],
      objectGrants: [
        {
          artifactId: "dataset-human-rnaseq",
          permission: "download",
          dataClass: "restricted_human_dataset",
          approvedUseCase: "",
        },
        {
          artifactId: "notebook-review-blinded",
          permission: "read",
          dataClass: "blind_review_material",
          approvedUseCase: "vendor-preview",
        },
      ],
      approvalEvents: ["requested"],
    },
    {
      id: "svc-manuscript-release",
      displayName: "Manuscript release assistant",
      kind: "service_account",
      ownerSponsorId: "u-admin-patel",
      requesterId: "u-admin-patel",
      requesterMfaVerified: true,
      integrationType: "internal_worker",
      integrationVerified: true,
      purpose: "Prepare manuscript release packets after reviewer signoff",
      requestedAt: "2026-05-10T18:00:00.000Z",
      expiresAt: "2026-06-15T00:00:00.000Z",
      lastRotatedAt: "2026-05-10T18:00:00.000Z",
      scopes: ["manuscript:publish", "dataset:read", "audit:append"],
      objectGrants: [
        {
          artifactId: "manuscript-v3",
          permission: "publish",
          dataClass: "manuscript",
          approvedUseCase: "accepted-release",
        },
        {
          artifactId: "dataset-human-rnaseq",
          permission: "read",
          dataClass: "restricted_human_dataset",
          approvedUseCase: "citation-verification",
        },
      ],
      approvalEvents: ["requested", "owner_approved", "security_reviewed"],
    },
  ],
}
