export const policy = {
  generatedAt: "2026-05-20T20:30:00.000Z",
  centsPerToken: 0.00004,
  centsPerWallMinute: 3.5,
  rawToDistinctInflationThreshold: 2.5,
}

export const accountControls = {
  "lab-northbridge": {
    plan: "Lab Pro",
    paymentRail: "card_subscription",
    includedComputeCents: 2,
    topUpBalanceCents: 15,
  },
  "lab-westlake": {
    plan: "Reproducibility Pack",
    paymentRail: "institutional_invoice",
    includedComputeCents: 25,
    topUpBalanceCents: 100,
  },
  "institute-helix": {
    plan: "Institutional License",
    paymentRail: "institutional_invoice",
    includedComputeCents: 1,
    topUpBalanceCents: 0,
  },
}

export const computeEvents = [
  {
    id: "evt-001",
    accountId: "lab-northbridge",
    requestId: "req-a1",
    operation: "literature_summary",
    lifecycle: "tool_use",
    status: "interrupted",
    model: "scibase-reviewer-v2",
    promptHash: "prompt-lit-review-crispr",
    params: { temperature: 0.1, maxOutputTokens: 1800 },
    toolName: "fetch_citation_graph",
    toolArgsHash: "toolargs-citation-crispr",
    sourceDocumentId: "doc-crispr-001",
    inputTokens: 2420,
    outputTokens: 420,
    wallClockMs: 12000,
    startedAt: "2026-05-20T09:00:10Z",
  },
  {
    id: "evt-002",
    accountId: "lab-northbridge",
    requestId: "req-a2",
    operation: "literature_summary",
    lifecycle: "retry",
    status: "success",
    model: "scibase-reviewer-v2",
    promptHash: "prompt-lit-review-crispr",
    params: { maxOutputTokens: 1800, temperature: 0.1 },
    toolName: "fetch_citation_graph",
    toolArgsHash: "toolargs-citation-crispr",
    sourceDocumentId: "doc-crispr-001",
    inputTokens: 2420,
    outputTokens: 1780,
    wallClockMs: 34000,
    startedAt: "2026-05-20T09:00:42Z",
  },
  {
    id: "evt-003",
    accountId: "lab-northbridge",
    requestId: "req-a2",
    operation: "literature_summary",
    lifecycle: "tool_result",
    status: "success",
    model: "scibase-reviewer-v2",
    promptHash: "prompt-lit-review-crispr",
    params: { temperature: 0.1, maxOutputTokens: 1800 },
    toolName: "fetch_citation_graph",
    toolArgsHash: "toolargs-citation-crispr",
    sourceDocumentId: "doc-crispr-001",
    inputTokens: 2420,
    outputTokens: 1780,
    wallClockMs: 34000,
    startedAt: "2026-05-20T09:01:16Z",
  },
  {
    id: "evt-004",
    accountId: "lab-westlake",
    requestId: "req-b1",
    operation: "reproducibility_check",
    lifecycle: "completion",
    status: "success",
    model: "scibase-runner-v1",
    promptHash: "prompt-notebook-rerun-metabolomics",
    params: { sandbox: "python-3.12", gpu: false },
    sourceDocumentId: "notebook-metabolomics-44",
    inputTokens: 900,
    outputTokens: 120,
    wallClockMs: 780000,
    reproducibility: { deterministic: false },
    startedAt: "2026-05-20T10:15:00Z",
  },
  {
    id: "evt-005",
    accountId: "lab-westlake",
    requestId: "req-b2",
    operation: "reproducibility_check",
    lifecycle: "completion",
    status: "success",
    model: "scibase-runner-v1",
    promptHash: "prompt-notebook-rerun-metabolomics",
    params: { sandbox: "python-3.12", gpu: false },
    sourceDocumentId: "notebook-metabolomics-44",
    inputTokens: 900,
    outputTokens: 118,
    wallClockMs: 770000,
    reproducibility: { deterministic: false },
    startedAt: "2026-05-20T10:32:00Z",
  },
  {
    id: "evt-006",
    accountId: "institute-helix",
    requestId: "req-c1",
    operation: "peer_review_triage",
    lifecycle: "completion",
    status: "success",
    model: "scibase-reviewer-v2",
    promptHash: "prompt-review-oncology-panel",
    params: { temperature: 0, rubric: "oncology" },
    sourceDocumentId: "grant-oncology-221",
    inputTokens: 4600,
    outputTokens: 800,
    wallClockMs: 21000,
    startedAt: "2026-05-20T12:00:00Z",
  },
  {
    id: "evt-007",
    accountId: "institute-helix",
    requestId: "req-c2",
    operation: "peer_review_triage",
    lifecycle: "cache_hit",
    status: "success",
    model: "scibase-reviewer-v2",
    promptHash: "prompt-review-oncology-panel",
    params: { temperature: 0, rubric: "oncology" },
    sourceDocumentId: "grant-oncology-221",
    inputTokens: 4600,
    outputTokens: 800,
    wallClockMs: 500,
    startedAt: "2026-05-20T12:04:00Z",
  },
  {
    id: "evt-008",
    accountId: "institute-helix",
    requestId: "req-c3",
    operation: "peer_review_triage",
    lifecycle: "cache_hit",
    status: "success",
    model: "scibase-reviewer-v2",
    promptHash: "prompt-review-oncology-panel",
    params: { temperature: 0, rubric: "oncology" },
    sourceDocumentId: "grant-oncology-221",
    inputTokens: 4600,
    outputTokens: 800,
    wallClockMs: 500,
    startedAt: "2026-05-20T12:05:00Z",
  },
  {
    id: "evt-009",
    accountId: "institute-helix",
    requestId: "req-c4",
    operation: "peer_review_triage",
    lifecycle: "cache_hit",
    status: "success",
    model: "scibase-reviewer-v2",
    promptHash: "prompt-review-oncology-panel",
    params: { temperature: 0, rubric: "oncology" },
    sourceDocumentId: "grant-oncology-221",
    inputTokens: 4600,
    outputTokens: 800,
    wallClockMs: 500,
    startedAt: "2026-05-20T12:06:00Z",
  },
  {
    id: "evt-010",
    accountId: "institute-helix",
    requestId: "req-c5",
    operation: "peer_review_triage",
    lifecycle: "cache_hit",
    status: "success",
    model: "scibase-reviewer-v2",
    promptHash: "prompt-review-oncology-panel",
    params: { temperature: 0, rubric: "oncology" },
    sourceDocumentId: "grant-oncology-221",
    inputTokens: 4600,
    outputTokens: 800,
    wallClockMs: 500,
    startedAt: "2026-05-20T12:07:00Z",
  },
]
