export const evidenceBindingInput = {
  manuscript: {
    id: "ms-climate-pulse-2026",
    title: "Urban heat pulses and clinical respiratory load",
    releaseId: "submission-freeze-2026-05-21",
    submissionState: "publication_ready",
    lockedAt: "2026-05-21T17:30:00Z",
    sections: [
      {
        id: "sec-results",
        title: "Results",
        versionHash: "sec_results_v12_8e0f",
        locked: true,
      },
      {
        id: "sec-methods",
        title: "Methods",
        versionHash: "sec_methods_v8_211c",
        locked: true,
      },
      {
        id: "sec-discussion",
        title: "Discussion",
        versionHash: "sec_discussion_v9_0b12",
        locked: false,
      },
    ],
    claims: [
      {
        id: "claim-heat-er",
        sectionId: "sec-results",
        type: "primary_result",
        text: "A two-day heat pulse increased respiratory emergency visits by 18%.",
        requiredEvidenceTypes: ["notebook_output", "dataset"],
        evidenceAnchorIds: ["ev-notebook-heat-er", "ev-dataset-er-visits"],
        citationKeys: ["rossi2025heat"],
      },
      {
        id: "claim-air-quality-control",
        sectionId: "sec-results",
        type: "control_result",
        text: "Air quality controls did not change the heat-pulse estimate.",
        requiredEvidenceTypes: ["notebook_output", "method_citation"],
        evidenceAnchorIds: ["ev-notebook-aq-control", "ev-method-control-model"],
        citationKeys: ["chen2024distributedlag"],
      },
      {
        id: "claim-causal-language",
        sectionId: "sec-discussion",
        type: "interpretation",
        text: "The intervention caused downstream clinic load to fall within one week.",
        requiredEvidenceTypes: ["notebook_output", "dataset"],
        evidenceAnchorIds: ["ev-notebook-intervention"],
        citationKeys: [],
      },
    ],
    assets: [
      {
        id: "fig-heat-response",
        kind: "figure",
        label: "Figure 2",
        sectionId: "sec-results",
        sourceAnchorIds: ["ev-notebook-heat-er"],
        caption: "Distributed lag response after two-day heat pulses.",
      },
      {
        id: "table-sensitivity",
        kind: "table",
        label: "Table 1",
        sectionId: "sec-results",
        sourceAnchorIds: ["ev-notebook-aq-control", "ev-dataset-er-visits"],
        caption: "Sensitivity checks with and without air quality controls.",
      },
      {
        id: "eq-risk-index",
        kind: "equation",
        label: "Equation 1",
        sectionId: "sec-methods",
        sourceAnchorIds: ["ev-method-control-model"],
        caption: "Distributed-lag risk index.",
      },
    ],
  },
  evidence: [
    {
      id: "ev-notebook-heat-er",
      type: "notebook_output",
      sectionId: "sec-results",
      title: "Notebook output: heat pulse respiratory visits",
      sourcePath: "analysis/heat_response.ipynb#cell-14",
      approvedDigest: "sha256:heat_er_output_20260521_1730",
      currentDigest: "sha256:heat_er_output_20260521_1730",
      upstreamDigests: ["sha256:er_visits_v5"],
      currentUpstreamDigests: ["sha256:er_visits_v5"],
      sectionVersionHash: "sec_results_v12_8e0f",
      citationKey: "rossi2025heat",
      doi: "10.5555/heat.2025.002",
      generatedAt: "2026-05-21T16:40:00Z",
      approvedAt: "2026-05-21T17:20:00Z",
      staleAfter: null,
      locked: true,
    },
    {
      id: "ev-dataset-er-visits",
      type: "dataset",
      sectionId: "sec-results",
      title: "Respiratory ER visit extract",
      sourcePath: "data/respiratory_er_visits.parquet",
      approvedDigest: "sha256:er_visits_v5",
      currentDigest: "sha256:er_visits_v5",
      sectionVersionHash: "sec_results_v12_8e0f",
      citationKey: "rossi2025heat",
      doi: "10.5555/heat-data.2025.004",
      generatedAt: "2026-05-20T18:00:00Z",
      approvedAt: "2026-05-21T16:00:00Z",
      license: "CC-BY-4.0",
      access: "controlled",
      locked: true,
    },
    {
      id: "ev-notebook-aq-control",
      type: "notebook_output",
      sectionId: "sec-results",
      title: "Notebook output: air quality controls",
      sourcePath: "analysis/air_quality_controls.ipynb#cell-22",
      approvedDigest: "sha256:aq_control_output_20260520",
      currentDigest: "sha256:aq_control_output_20260521_changed",
      upstreamDigests: ["sha256:er_visits_v5", "sha256:aq_panel_v3"],
      currentUpstreamDigests: ["sha256:er_visits_v5", "sha256:aq_panel_v4"],
      sectionVersionHash: "sec_results_v12_8e0f",
      citationKey: "chen2024distributedlag",
      doi: "10.5555/dlag.2024.019",
      generatedAt: "2026-05-20T21:10:00Z",
      approvedAt: "2026-05-21T10:00:00Z",
      staleAfter: "2026-05-21T12:15:00Z",
      locked: true,
    },
    {
      id: "ev-method-control-model",
      type: "method_citation",
      sectionId: "sec-methods",
      title: "Distributed lag model reference",
      sourcePath: "references.bib#chen2024distributedlag",
      approvedDigest: "sha256:method_ref_chen_2024_v1",
      currentDigest: "sha256:method_ref_chen_2024_v1",
      sectionVersionHash: "sec_methods_v8_211c",
      citationKey: "chen2024distributedlag",
      doi: "10.5555/dlag.2024.019",
      generatedAt: "2026-05-18T10:00:00Z",
      approvedAt: "2026-05-21T09:30:00Z",
      locked: true,
    },
    {
      id: "ev-notebook-intervention",
      type: "notebook_output",
      sectionId: "sec-discussion",
      title: "Notebook output: intervention subgroup",
      sourcePath: "analysis/intervention_subgroup.ipynb#cell-31",
      approvedDigest: "sha256:intervention_output_v1",
      currentDigest: "sha256:intervention_output_v1",
      upstreamDigests: ["sha256:intervention_panel_v2"],
      currentUpstreamDigests: ["sha256:intervention_panel_v2"],
      sectionVersionHash: "sec_discussion_v8_old",
      citationKey: null,
      doi: null,
      generatedAt: "2026-05-19T12:00:00Z",
      approvedAt: null,
      locked: false,
    },
  ],
}
